MoneyRate/Models/ErrorViewModel.cs
namespace MoneyRate.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MoneyRate/Models/Rate.cs
using System.ComponentModel.DataAnnotations;

namespace MoneyRate.Models
{
    public class Rate
    {
        [Key]
        public int Id { get; set; }
        [Required]                       //обязательное заполнение этого поля 
        [StringLength(50)]
        [Display(Name = "Country Name")]
        public string CountryName { get; set; }

        public float CountryRate { get; set; }

        public string CurrencyName { get; set; }
        public int OnMainPage { get; set; }
    }
}

MoneyRate/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MoneyRate.Models;
using System.Diagnostics;

namespace MoneyRate.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MoneyRate/Controllers/RateController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoneyRate.Data;
using MoneyRate.Models;

namespace MoneyRate.Controllers
{
    public class RateController : Controller
    {
        private readonly ApplicationDbContext _db;

        public RateController(ApplicationDbContext db)
        {
            _db = db;       //даем доступ к базе данных
        }

        //GET 
        public async Task<IActionResult> Index(string SearchString)
        {   
            //var mainRates = _db.Rate.FromSqlRaw<Rate>("SELECT * FROM Rate WHERE OnMainPage = '1'");

            //rateList = _db.Rate;      //записываем наши Rate в бд и передаем в представления

            var rates = from m in _db.Rate          //создает запрос LINQ и выводит
                        select m;

            //var rates = _db.Rate.FromSqlRaw<Rate>("SELECT * FROM Rate WHERE CountryName = 'SearchString'");

            if (!String.IsNullOrEmpty(SearchString))        //если содержит строку, то меняется запрос
            {
                rates = rates.Where(s => s.CountryName!.Contains(SearchString));
            }

            return View(await rates.ToListAsync());
        }

        //POST
        [HttpPost]
        public string Index(string searchString, bool notUsed)  //Параметр notUsed используется для создания перегрузки Index метода
        {
            return "From [HttpPost]Index: filter on " + searchString;   //делая запрос, мы переходим на новую страницу с 
                                                                        //отфильтрованными данными, а не перезагружаем страницу
        }

        //BUY - EDIT
        public IActionResult Buy()
        {
            return View();
        }

        //BUY - POST


    }
}

MoneyRate/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MoneyRate/Views/Rate/Buy.cshtml
@model Rate    //для доступа списка Rate  в нашем представлении

@{
    ViewBag.Title = "Buy";
}
<!DOCTYPE HTML>
<html>

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="~/css/style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="~/js/Convert.js"></script>
</head>

<body onload="startTime()">

<div id="time"></div>

<form asp-controller="Rate" asp-action="Buy" method ="get">          <!--строка поиска-->
    <p>
        Enter amount: <input type="text" name="enterAmount" />
    </p>
    
    <div class="col-8">
        From:
        <input asp-for="CurrencyName" class="form-control" />
        <span asp-validation-for="CurrencyName" class="text-danger"></span>                 <!--в этом месте будут отображаться сообщения об ошибках для Name-->
    </div>

    <p>
        <input type="submit" value="Transfer" />
        
    </p>

    <div class="col-8">
        To:
        <input asp-for="CurrencyName" class="form-control" />
        <span asp-validation-for="CurrencyName" class="text-danger"></span>                 <!--в этом месте будут отображаться сообщения об ошибках для Name-->
    </div>

</form>

<div id="div1">Result:
    <div id="div2">  </div>
</div>



</body>

</html>

MoneyRate/Views/Rate/Index.cshtml
@model IEnumerable<Rate>    //для доступа списка Rate  в нашем представлении

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Chek Rate</h2>
        </div>
    </div>

    <br /><br />
        
    <form asp-controller="Rate" asp-action="Index" method ="get">          <!--строка поиска-->
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />
    </p>
    </form>

    @if (Model.Count() > 0) //использование Razor и проверяет на наличие обьекта в списке
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Country Name
                    </th>
                    <th>
                        Country Rate
                    </th>
                    <th>
                        Currency Name
                    </th>
                    <th>
                        
                    </th>
                </tr>
            </thead>
            <tbody>
                <!--перечисление Category-->
                @foreach (var obj in Model)
                {
                    <tr>
                        <td width="40%">@obj.CountryName</td>
                        <td width="30%">@obj.CountryRate</td>
                        <td width="20%">@obj.CurrencyName</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Rate" asp-action="Buy" class="btn btn-primary mx-2">
                                    Buy
                                    <i class="fas fa-edit"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    
                }
            </tbody>
        </table>
    }

    else
    {
        <p> Country not exist.</p>
    }

</div>

MoneyRate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoneyRate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoneyRate.styles.css" asp-append-version="true" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoneyRate</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rate" asp-action="Index">Rate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MoneyRate - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>